name: common
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
