name: chapter_6_queues
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

dependencies:
  common:
    path: ../common
